---
title: "Curriculum Vitae"
---

---

## **Relevant Education**

---

#### **Since October 2015 - ongoing:**

**PhD student in Ecology with specialization in Marine Microbial Ecology**, under supervision of [**Prof. Jarone Pinhassi**](https://lnu.se/en/staff/jarone.pinhassi/), [**Ass. Prof. Daniel Lundin**](https://lnu.se/en/staff/daniel.lundin/) and [**Prof. Catherine Legrand**](https://lnu.se/en/staff/catherine.legrand/), Linnaeus University, Centre for Ecology and Evolution in Microbial model Systems (EEMiS), Faculty of Health and Life Sciences, Barlastgatan 11, 39182 Kalmar, Sweden.

---

#### **Between September 2018 and February 2016**

**GENECO student**, Graduate Research School in Genomic Ecology, Faculty of Science, Department of Biology, Lund University, Sweden.

---

#### **Between June 2015 and March 2013:**

**MSc in Ecology with main focus on Marine Biology, Microbial Oceanography**, under supervision of [**Prof. Gerhard J. Herndl**](https://limbo.univie.ac.at/research/microbial-oceanography/) and Senior Scientist [**Dr. Thomas Reinthaler**](http://www.microbial-oceanography.eu/thomas-reinthaler/), and [**Alexander H. Frank**](https://www.whoi.edu/profile/afrank), University of Vienna, Department of Limnology and Biological Oceanography, Centre of Ecology, University of Vienna, Althanstraße 14, 1090 Vienna, Austria.

---

#### **Between February 2013 and October 2009:**

**BSc in Biology**, University of Vienna, Althanstraße 14, 1090 Vienna, Austria.

---