---
title: "Publications"
---

---

> ###**Current ongoing projects - 2020**

* Distinct responses in bacterioplankton community structure, activity, and gene expression to dissolved organic matter compounds of different complexity (in prep.)(see <a href="project1.html">**Project1**</a>)

* Pronounced differences in bacterioplankton gene expression and community composition of a pre- and post-phytoplankton bloom in an upwelling system (in prep.)(see <a href="project2.html">**Project2**</a>)

* Microbial mediated processes in a stratified ecosystem and the assessment of the microbial community composition in the Gullmar Fjord (in prep.)(see <a href="project3.html">**Project3**</a>)

> ###**2016**

* [Erythromycin and GC7 fail as domain-specific inhibitors for bacterial and archaeal activity in the open ocean](http://www.int-res.com/abstracts/ame/v77/n2/p99-110/)

> ###**2020**

* [Labile dissolved organic matter compound characteristics select for divergence in marine bacterial activity and transcription](submitted to Frontiers)

---

> New exciting studies are in progress and I'll post the links here as soon as they are available!</p>
> Stay tuned!